import { dayShift } from './date';
import { createId } from './ids';
import { presetMedications } from '../data/presetPlan';
import type { DailyTask, Medication, MedicationDose, TreatmentPlan } from '../types/domain';

const doseKey = (dose: Pick<MedicationDose, 'medicationId' | 'date' | 'plannedTime'>) => `${dose.medicationId}|${dose.date}|${dose.plannedTime}`;

const getMedicationDays = (medication: Medication): number[] => {
  if (medication.specificDays?.length) {
    return [...medication.specificDays].sort((a, b) => a - b);
  }

  const start = medication.startDay ?? 1;
  const duration = medication.durationDays ?? 1;
  return Array.from({ length: duration }, (_, index) => start + index);
};

const createScheduledDose = (medicationId: string, date: string, time: string): MedicationDose => ({
  id: createId('dose'),
  medicationId,
  date,
  plannedTime: time,
  currentTime: time,
  status: 'scheduled',
  isAutoGenerated: true
});

export const generateDosesForMedications = (startDate: string, medications: Medication[]): MedicationDose[] => {
  return medications.flatMap((medication) => {
    const days = getMedicationDays(medication);
    const times = medication.defaultTimes.length ? medication.defaultTimes : ['08:00'];

    return days.flatMap((day) => {
      const date = dayShift(startDate, day - 1);
      return times.map((time) => createScheduledDose(medication.id, date, time));
    });
  });
};

export const rebuildPlanDoses = (plan: TreatmentPlan): TreatmentPlan => {
  const generatedDoses = generateDosesForMedications(plan.startDate, plan.medications);
  const existingByKey = new Map(plan.doses.map((dose) => [doseKey(dose), dose]));

  return {
    ...plan,
    doses: generatedDoses.map((dose) => {
      const existing = existingByKey.get(doseKey(dose));
      if (!existing) return dose;
      return {
        ...dose,
        status: existing.status,
        currentTime: existing.currentTime,
        instruction: existing.instruction
      };
    })
  };
};

export const buildInitialPlan = (startDate: string): TreatmentPlan => {
  const doses = generateDosesForMedications(startDate, presetMedications.filter((medication) => !['maxilac', 'clindacin', 'acylact'].includes(medication.id)));

  const tasks: DailyTask[] = [
    {
      id: createId('task'),
      date: startDate,
      title: 'Старт лечения',
      type: 'treatment-stage',
      completed: false,
      details: 'Схема на первые 30 дней сформирована автоматически'
    }
  ];

  return {
    id: createId('plan'),
    startDate,
    medications: presetMedications,
    doses,
    tasks,
    customEvents: []
  };
};

export const applyPostMenstrualStage = (plan: TreatmentPlan, endDate: string): TreatmentPlan => {
  const courseStart = dayShift(endDate, 1);
  const postStageMedications = plan.medications.filter((medication) => ['maxilac', 'clindacin', 'acylact'].includes(medication.id));
  const generated = generateDosesForMedications(courseStart, postStageMedications);

  const deduped = [...plan.doses, ...generated].filter(
    (dose, index, all) => all.findIndex((other) => doseKey(other) === doseKey(dose)) === index
  );

  return {
    ...plan,
    doses: deduped,
    tasks: [
      ...plan.tasks,
      {
        id: createId('task'),
        date: courseStart,
        title: 'Постменструальный этап',
        type: 'treatment-stage',
        completed: false,
        details: 'Максилак + Клиндацин + Ацилакт'
      }
    ]
  };
};