import { dayShift } from './date';
import { createId } from './ids';
import { presetMedications } from '../data/presetPlan';
import type { DailyTask, MedicationDose, TreatmentPlan } from '../types/domain';

interface Rule {
  medicationId: string;
  days: number[];
  time: string;
  instruction?: string;
}

const dayRange = (start: number, end: number): number[] => Array.from({ length: end - start + 1 }, (_, i) => i + start);

const rules: Rule[] = [
  { medicationId: 'doxycycline', days: dayRange(1, 7), time: '08:00' },
  { medicationId: 'doxycycline', days: dayRange(1, 7), time: '20:00' },
  { medicationId: 'duphaston', days: dayRange(1, 10), time: '08:00' },
  { medicationId: 'duphaston', days: dayRange(1, 10), time: '20:00' },
  { medicationId: 'tranexam', days: dayRange(1, 3), time: '08:00' },
  { medicationId: 'tranexam', days: dayRange(1, 3), time: '15:00' },
  { medicationId: 'tranexam', days: dayRange(1, 3), time: '20:00' },
  { medicationId: 'indomethacin', days: dayRange(1, 5), time: '20:00' },
  { medicationId: 'fluconazole', days: [1, 4], time: '20:00' },
  { medicationId: 'vitamin-d', days: dayRange(1, 30), time: '08:00' }
];

export const buildInitialPlan = (startDate: string): TreatmentPlan => {
  const doses: MedicationDose[] = [];
  rules.forEach((rule) => {
    rule.days.forEach((day) => {
      const date = dayShift(startDate, day - 1);
      doses.push({
        id: createId('dose'),
        medicationId: rule.medicationId,
        date,
        plannedTime: rule.time,
        currentTime: rule.time,
        status: 'scheduled',
        isAutoGenerated: true,
        instruction: rule.instruction
      });
    });
  });

  const tasks: DailyTask[] = [
    {
      id: createId('task'),
      date: startDate,
      title: 'Старт лечения',
      type: 'treatment-stage',
      completed: false,
      details: 'Схема на первые 30 дней сформирована автоматически'
    }
  ];

  return {
    id: createId('plan'),
    startDate,
    medications: presetMedications,
    doses,
    tasks,
    customEvents: []
  };
};

export const applyPostMenstrualStage = (plan: TreatmentPlan, endDate: string): TreatmentPlan => {
  const courseStart = dayShift(endDate, 1);
  const extraRules: Rule[] = [
    { medicationId: 'maxilac', days: dayRange(1, 30), time: '08:00' },
    { medicationId: 'clindacin', days: dayRange(1, 6), time: '23:00' },
    { medicationId: 'acylact', days: dayRange(7, 16), time: '23:00' }
  ];

  const generated = extraRules.flatMap((rule) =>
    rule.days.map((day) => ({
      id: createId('dose'),
      medicationId: rule.medicationId,
      date: dayShift(courseStart, day - 1),
      plannedTime: rule.time,
      currentTime: rule.time,
      status: 'scheduled' as const,
      isAutoGenerated: true
    }))
  );

  const deduped = [...plan.doses, ...generated].filter(
    (dose, index, all) =>
      all.findIndex(
        (other) => other.date === dose.date && other.medicationId === dose.medicationId && other.plannedTime === dose.plannedTime
      ) === index
  );

  return {
    ...plan,
    doses: deduped,
    tasks: [
      ...plan.tasks,
      {
        id: createId('task'),
        date: courseStart,
        title: 'Постменструальный этап',
        type: 'treatment-stage',
        completed: false,
        details: 'Максилак + Клиндацин + Ацилакт'
      }
    ]
  };
};
