import { addDays, differenceInCalendarDays } from 'date-fns';
import { dayShift, fromISODate, toISODate } from './date';
import { createId } from './ids';
import { presetMedications } from '../data/presetPlan';
import type { DailyTask, Medication, MedicationDose, TreatmentPlan } from '../types/domain';

const doseKey = (dose: Pick<MedicationDose, 'medicationId' | 'date' | 'plannedTime'>) => `${dose.medicationId}|${dose.date}|${dose.plannedTime}`;

const getSortedUniqueDates = (dates: string[]) => [...new Set(dates)].sort((a, b) => a.localeCompare(b));

const getManualDates = (medication: Medication, fallbackStartDate: string): string[] => {
  if (medication.manualDates?.length) {
    return getSortedUniqueDates(medication.manualDates);
  }

  if (medication.specificDays?.length) {
    const medicationStartDate = medication.startDate ?? fallbackStartDate;
    return getSortedUniqueDates(
      [...medication.specificDays]
        .sort((a, b) => a - b)
        .map((day) => dayShift(medicationStartDate, day - 1))
    );
  }

  return [];
};

const getContinuousDates = (medication: Medication, fallbackStartDate: string): string[] => {
  const startDate = medication.startDate ?? fallbackStartDate;
  const normalizedDuration = Math.max(medication.durationDays ?? 1, 1);

  if (medication.endDate) {
    const diff = differenceInCalendarDays(fromISODate(medication.endDate), fromISODate(startDate));
    const span = Math.max(diff + 1, 1);
    return Array.from({ length: span }, (_, index) => toISODate(addDays(fromISODate(startDate), index)));
  }

  return Array.from({ length: normalizedDuration }, (_, index) => dayShift(startDate, index));
};

const getMedicationDates = (medication: Medication, fallbackStartDate: string): string[] => {
  const isManual = medication.scheduleMode === 'manual' || Boolean(medication.manualDates?.length) || Boolean(medication.specificDays?.length);
  return isManual ? getManualDates(medication, fallbackStartDate) : getContinuousDates(medication, fallbackStartDate);
};

const createScheduledDose = (medicationId: string, date: string, time: string): MedicationDose => ({
  id: createId('dose'),
  medicationId,
  date,
  plannedTime: time,
  currentTime: time,
  status: 'scheduled',
  isAutoGenerated: true
});

export const generateDosesForMedications = (startDate: string, medications: Medication[]): MedicationDose[] => {
  return medications.flatMap((medication) => {
    const dates = getMedicationDates(medication, startDate);
    const times = medication.defaultTimes.length ? medication.defaultTimes : ['08:00'];

    return dates.flatMap((date) => times.map((time) => createScheduledDose(medication.id, date, time)));
  });
};

export const rebuildPlanDoses = (plan: TreatmentPlan): TreatmentPlan => {
  const generatedDoses = generateDosesForMedications(plan.startDate, plan.medications);
  const existingByKey = new Map(plan.doses.map((dose) => [doseKey(dose), dose]));

  return {
    ...plan,
    doses: generatedDoses.map((dose) => {
      const existing = existingByKey.get(doseKey(dose));
      if (!existing) return dose;
      return {
        ...dose,
        status: existing.status,
        currentTime: existing.currentTime,
        instruction: existing.instruction
      };
    })
  };
};

export const buildInitialPlan = (startDate: string): TreatmentPlan => {
  const medications = presetMedications.map((medication) => ({
    ...medication,
    startDate: medication.startDate ?? startDate,
    scheduleMode: medication.scheduleMode ?? (medication.specificDays?.length ? 'manual' : 'continuous')
  }));
  const doses = generateDosesForMedications(startDate, medications.filter((medication) => !['maxilac', 'clindacin', 'acylact'].includes(medication.id)));

  const tasks: DailyTask[] = [
    {
      id: createId('task'),
      date: startDate,
      title: 'Старт лечения',
      type: 'treatment-stage',
      completed: false,
      details: 'Схема на первые 30 дней сформирована автоматически'
    }
  ];

  return {
    id: createId('plan'),
    startDate,
    medications,
    doses,
    tasks,
    customEvents: []
  };
};

export const applyPostMenstrualStage = (plan: TreatmentPlan, endDate: string): TreatmentPlan => {
  const courseStart = dayShift(endDate, 1);
  const postStageMedications = plan.medications
    .filter((medication) => ['maxilac', 'clindacin', 'acylact'].includes(medication.id))
    .map((medication) => ({ ...medication, startDate: courseStart }));
  const generated = generateDosesForMedications(courseStart, postStageMedications);

  const deduped = [...plan.doses, ...generated].filter(
    (dose, index, all) => all.findIndex((other) => doseKey(other) === doseKey(dose)) === index
  );

  return {
    ...plan,
    doses: deduped,
    tasks: [
      ...plan.tasks,
      {
        id: createId('task'),
        date: courseStart,
        title: 'Постменструальный этап',
        type: 'treatment-stage',
        completed: false,
        details: 'Максилак + Клиндацин + Ацилакт'
      }
    ]
  };
};
