export type MoodLevel = 'excellent' | 'normal' | 'not-great' | 'bad';
export type IntakeStatus = 'scheduled' | 'done' | 'skipped' | 'postponed';
export type IntakeKind = 'tablet' | 'capsule' | 'suppository' | 'vitamin';
export type BleedingLevel = 'none' | 'light' | 'moderate' | 'heavy';

export interface Medication {
  id: string;
  name: string;
  dosage: string;
  quantity: string;
  intakeKind: IntakeKind;
  withFood: 'before' | 'during' | 'after' | 'any';
  notes: string[];
  warnings?: string[];
  defaultTimes: string[];
  durationDays?: number;
}

export interface MedicationDose {
  id: string;
  medicationId: string;
  date: string;
  plannedTime: string;
  currentTime: string;
  status: IntakeStatus;
  isAutoGenerated: boolean;
  instruction?: string;
}

export interface DailyTask {
  id: string;
  date: string;
  title: string;
  type: 'treatment-stage' | 'cycle' | 'custom';
  completed: boolean;
  details?: string;
}

export interface SymptomEntry {
  date: string;
  painLevel: number;
  bleeding: BleedingLevel;
  temperature?: number;
  nausea: boolean;
  weakness: boolean;
  dizziness: boolean;
  discharge: boolean;
  mood: MoodLevel;
  sleepHours?: number;
  appetite: 'low' | 'normal' | 'high';
  alarmingSymptoms: string[];
  comment?: string;
}

export interface CycleEntry {
  id: string;
  startDate: string;
  endDate?: string;
  isEstimated?: boolean;
}

export interface NoteEntry {
  date: string;
  text: string;
}

export interface TreatmentPlan {
  id: string;
  startDate: string;
  medications: Medication[];
  doses: MedicationDose[];
  tasks: DailyTask[];
  customEvents: DailyTask[];
}

export interface AppSettings {
  appName: 'Нежный Календарик' | 'Забота рядом' | 'Тихий Ритм' | 'Лепесток';
  profileName: 'Солнышко' | 'Любимая' | 'Котик';
  notificationsEnabled: boolean;
  showCyclovitaTrack: boolean;
  disclaimerSeen: boolean;
}

export interface AppState {
  version: number;
  onboardingCompleted: boolean;
  treatmentPlan: TreatmentPlan | null;
  cycleEntries: CycleEntry[];
  symptomsByDate: Record<string, SymptomEntry>;
  notesByDate: Record<string, NoteEntry>;
  settings: AppSettings;
}

export interface ExportedBackup {
  exportedAt: string;
  source: 'Нежный Календарик';
  version: number;
  payload: Partial<AppState>;
}
